import type { ExerciseRecord } from './exerciseData';

type MachineDefinition = {
  name: string;
  target: string;
  bodyPart: string;
  family: 'Plate-Loaded' | 'Ground Base' | 'Select' | 'MTS';
};

const machines: MachineDefinition[] = [
  { name: 'Iso-Lateral Row', target: 'back', bodyPart: 'upper body', family: 'Plate-Loaded' },
  { name: 'Linear Leg Press', target: 'quadriceps', bodyPart: 'lower body', family: 'Plate-Loaded' },
  { name: 'Glute Drive', target: 'glutes', bodyPart: 'lower body', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Incline Press', target: 'upper chest', bodyPart: 'chest', family: 'Plate-Loaded' },
  { name: 'Gripper', target: 'forearms', bodyPart: 'lower arms', family: 'Plate-Loaded' },
  { name: 'Tibia Dorsi Flexion', target: 'tibialis anterior', bodyPart: 'lower legs', family: 'Plate-Loaded' },
  { name: 'Seated Calf Raise', target: 'calves', bodyPart: 'lower legs', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Horizontal Bench Press', target: 'chest', bodyPart: 'chest', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Bench Press', target: 'chest', bodyPart: 'chest', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Chest/Back', target: 'chest and back', bodyPart: 'upper body', family: 'Plate-Loaded' },
  { name: 'Belt Squat', target: 'quadriceps', bodyPart: 'lower body', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Shoulder Press', target: 'shoulders', bodyPart: 'shoulders', family: 'Plate-Loaded' },
  { name: 'Abdominal Oblique Crunch', target: 'abdominals', bodyPart: 'core', family: 'Plate-Loaded' },
  { name: 'Seated Biceps', target: 'biceps', bodyPart: 'upper arms', family: 'Plate-Loaded' },
  { name: 'Pendulum-X Squat', target: 'quadriceps', bodyPart: 'lower body', family: 'Plate-Loaded' },
  { name: 'Hack Squat', target: 'quadriceps', bodyPart: 'lower body', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Decline Chest Press', target: 'lower chest', bodyPart: 'chest', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Kneeling Leg Curl', target: 'hamstrings', bodyPart: 'upper legs', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Leg Extension', target: 'quadriceps', bodyPart: 'upper legs', family: 'Plate-Loaded' },
  { name: 'Seated Dip', target: 'triceps', bodyPart: 'upper arms', family: 'Plate-Loaded' },
  { name: 'Pullover', target: 'lats', bodyPart: 'back', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Wide Pulldown', target: 'lats', bodyPart: 'back', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Low Row', target: 'back', bodyPart: 'back', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral D.Y. Row', target: 'back', bodyPart: 'back', family: 'Plate-Loaded' },
  { name: 'Super Squat Press', target: 'quadriceps and glutes', bodyPart: 'lower body', family: 'Plate-Loaded' },
  { name: 'Super Fly', target: 'chest', bodyPart: 'chest', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral High Row', target: 'upper back', bodyPart: 'back', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Wide Chest', target: 'chest', bodyPart: 'chest', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Super Incline Press', target: 'upper chest', bodyPart: 'chest', family: 'Plate-Loaded' },
  { name: 'V-Squat', target: 'quadriceps and glutes', bodyPart: 'lower body', family: 'Plate-Loaded' },
  { name: '4 Way Neck', target: 'neck', bodyPart: 'neck', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Leg Curl', target: 'hamstrings', bodyPart: 'upper legs', family: 'Plate-Loaded' },
  { name: 'Seated/Standing Shrug', target: 'traps', bodyPart: 'back', family: 'Plate-Loaded' },
  { name: 'Iso-Lateral Front Lat Pulldown', target: 'lats', bodyPart: 'back', family: 'Plate-Loaded' },
  { name: 'Fixed Pad Glute/Ham', target: 'glutes and hamstrings', bodyPart: 'lower body', family: 'Plate-Loaded' },
  { name: 'Lateral Raise', target: 'shoulders', bodyPart: 'shoulders', family: 'Plate-Loaded' },
  { name: 'Assisted Nordic Ham', target: 'hamstrings', bodyPart: 'upper legs', family: 'Plate-Loaded' },
  { name: 'Glute Ham Reverse Hyper Combo', target: 'posterior chain', bodyPart: 'lower body', family: 'Plate-Loaded' },
  { name: 'T-Bar Row', target: 'back', bodyPart: 'back', family: 'Plate-Loaded' },
  { name: 'Multi-Squat', target: 'quadriceps and glutes', bodyPart: 'lower body', family: 'Ground Base' },
  { name: 'Combo Twist', target: 'obliques', bodyPart: 'core', family: 'Ground Base' },
  { name: 'Jammer', target: 'full body', bodyPart: 'full body', family: 'Ground Base' },
  { name: 'Squat / High Pull', target: 'full body', bodyPart: 'full body', family: 'Ground Base' },
  { name: 'Dual Pulldown/Row', target: 'back', bodyPart: 'back', family: 'Select' },
  { name: 'Leg Extension', target: 'quadriceps', bodyPart: 'upper legs', family: 'Select' },
  { name: 'Assist Dip Chin', target: 'back and triceps', bodyPart: 'upper body', family: 'Select' },
  { name: 'Seated Leg Curl', target: 'hamstrings', bodyPart: 'upper legs', family: 'Select' },
  { name: 'Lat Pulldown', target: 'lats', bodyPart: 'back', family: 'Select' },
  { name: 'Pectoral Fly', target: 'chest', bodyPart: 'chest', family: 'Select' },
  { name: 'Biceps Curl', target: 'biceps', bodyPart: 'upper arms', family: 'Select' },
  { name: 'Horizontal Calf', target: 'calves', bodyPart: 'lower legs', family: 'Select' },
  { name: 'Hip and Glute', target: 'glutes', bodyPart: 'lower body', family: 'Select' },
  { name: 'Back Extension', target: 'lower back', bodyPart: 'back', family: 'Select' },
  { name: 'Chest Press', target: 'chest', bodyPart: 'chest', family: 'Select' },
  { name: 'Pectoral Fly / Rear Deltoid', target: 'chest and rear deltoids', bodyPart: 'upper body', family: 'Select' },
  { name: 'Fixed Pulldown', target: 'lats', bodyPart: 'back', family: 'Select' },
  { name: 'Hip Abduction', target: 'hip abductors', bodyPart: 'upper legs', family: 'Select' },
  { name: 'Hip Adduction', target: 'hip adductors', bodyPart: 'upper legs', family: 'Select' },
  { name: 'Leg Curl', target: 'hamstrings', bodyPart: 'upper legs', family: 'Select' },
  { name: 'Lateral Raise', target: 'shoulders', bodyPart: 'shoulders', family: 'Select' },
  { name: 'Seated Row', target: 'back', bodyPart: 'back', family: 'Select' },
  { name: 'Standing Calf', target: 'calves', bodyPart: 'lower legs', family: 'Select' },
  { name: 'Seated Leg Press', target: 'quadriceps and glutes', bodyPart: 'lower body', family: 'Select' },
  { name: 'Shoulder Press', target: 'shoulders', bodyPart: 'shoulders', family: 'Select' },
  { name: 'Triceps Extension', target: 'triceps', bodyPart: 'upper arms', family: 'Select' },
  { name: 'Abdominal Crunch', target: 'abdominals', bodyPart: 'core', family: 'Select' },
  { name: 'Iso-Lateral Biceps Curl', target: 'biceps', bodyPart: 'upper arms', family: 'MTS' },
  { name: 'Iso-Lateral Chest Press', target: 'chest', bodyPart: 'chest', family: 'MTS' },
  { name: 'Iso-Lateral Decline Press', target: 'lower chest', bodyPart: 'chest', family: 'MTS' },
  { name: 'Iso-Lateral Front Pulldown', target: 'lats', bodyPart: 'back', family: 'MTS' },
  { name: 'Iso-Lateral High Row', target: 'upper back', bodyPart: 'back', family: 'MTS' },
  { name: 'Iso-Lateral Incline Press', target: 'upper chest', bodyPart: 'chest', family: 'MTS' },
  { name: 'Iso-Lateral Row', target: 'back', bodyPart: 'back', family: 'MTS' },
  { name: 'Leg Extension', target: 'quadriceps', bodyPart: 'upper legs', family: 'MTS' },
  { name: 'Kneeling Leg Curl', target: 'hamstrings', bodyPart: 'upper legs', family: 'MTS' },
  { name: 'Iso-Lateral Shoulder Press', target: 'shoulders', bodyPart: 'shoulders', family: 'MTS' },
  { name: 'Iso-Lateral Triceps Extension', target: 'triceps', bodyPart: 'upper arms', family: 'MTS' },
  { name: 'Abdominal Crunch', target: 'abdominals', bodyPart: 'core', family: 'MTS' },
];

export const hammerStrengthExercises: ExerciseRecord[] = machines.map(
  (machine, index) => ({
    id: `hammer-strength-${machine.family.toLowerCase().replace(' ', '-')}-${index + 1}`,
    name: `Hammer Strength ${machine.family} ${machine.name}`,
    category: 'strength',
    body_part: machine.bodyPart,
    equipment: `Hammer Strength ${machine.family}`,
    muscle_group: machine.target,
    target: machine.target,
    instruction_steps: {
      en: [
        'Adjust the seat, pads, and starting position to fit your body and the machine placard.',
        'Select or load an appropriate resistance and secure all plates and pins.',
        'Brace your body, move through a controlled comfortable range, and avoid bouncing the weight.',
        'Return slowly to the starting position while keeping control of the resistance.',
      ],
    },
    attribution: 'Machine naming and product photo © Life Fitness / Hammer Strength. Photo loaded from the official Life Fitness catalog.',
  })
);
